### ISSUE TITLE
Plugin 'Basil WS (RN)' is not supported by the selected application

### ISSUE THREAD

**Issue by hmeerlo** [Matju-M/flipper-plugin-basil-ws#4]
I followed your instructions. Added the require to the bootstrap and installed the plugin. But I can not get it to work. Flipper keeps giving me this message: `Plugin 'Basil WS (RN)' is not supported by the selected application`

Any tips?

**Comment by Matju-M** [comment]
What versions are you using for react-native? I haven't tested it out with the new architecture, 0.69+ but should not really be an issue. Can you create a reproduction repo? So I can see the issue? @hmeerlo

**Comment by hmeerlo** [comment]
@Matju-M I'm really sorry for my way too late reply. Hope this can still help fix the issue. My react-native versions is 0.67.4. But what I gather from your response is that I should at least upgrade to 0.69+ since that has been tested?

**Comment by Matju-M** [comment]
Hi, it should work on 0.67, its the same as I tested. Are you able to replicate it in an example repo?

**Comment by hmeerlo** [comment]
I would really love to do that but I just can not afford the time at the moment. And I'm pretty sure that it will work then. It is most likely something in the way our project is setup. It is a quite complex project. So if you can give me some pointers to debug the problem then maybe I can find the problem myself?

**Comment by hmeerlo** [comment]
Does it matter that my application uses Socket.io instead of raw websockets? I do see that socket.io uses websockets in the application, it does not use long polling.

**Comment by hmeerlo** [comment]
Ok, I'll be damned. I determined to revisit the issue and try it all again. So I upgraded my Flipper from 0.179 to 0.182 and now it works! So feel free to close the issue, I really have no clue why this failed.

**Comment by Matju-M** [comment]
So, essentially, this library is for raw websockets. I believe there is another library that works with socket.io. Also, the issue that you have is unrelated to the websockets / socket.io implementation.
